name: Deploy Development Branch

on:
  push:
    branches: [ development ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install and build
        run: |
          R -e 'install.packages("shinylive")'
          R -e 'shinylive::export(".", "docs-dev")'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dev
          destination_dir: dev
