name: build-shinylive
on: [push]              # rebuild on every git push
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: |
          Rscript -e 'install.packages("shinylive")'
          Rscript -e 'shinylive::export(appdir=".", destdir="dist", include_assets="www")'
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
