name: build-shinylive
on: [push]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1Check out your repo
      - uses: actions/checkout@v4

      # 2Install core R toolchain
      - uses: r-lib/actions/setup-r@v2

      # 3NEW: system packages needed by archive / gh / pkgcache
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libarchive-dev \
            libcurl4-openssl-dev \
            libgit2-dev \
            libssl-dev \
            zlib1g-dev

      # 4Install shinylive from CRAN
      - name: Install shinylive
        run: |
          Rscript -e 'options(repos = c(CRAN="https://cloud.r-project.org"))' -e 'install.packages("shinylive")'

      # 5Build the static bundle
      - name: Build shinylive bundle
        run: |
          Rscript -e 'shinylive::export(appdir=".", destdir="dist", include_assets="www")'

      # 6Upload dist/ for GitHub Pages (action v3)
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
